#!/bin/bash
sync() {
mkdir -p ~/power
cd ~/power
git config --global user.name "ij_israfil"
git config --global user.email "israfilkhan494@gmail.com"
curl -LSs https://raw.githubusercontent.com/shravansayz/build_scripts/refs/heads/16/luna.sh | bash
}

echo "Syncing Rom and Device Sources..."
sync
echo "Syncing"
echo "Syncing...."
echo "Syncing......Done"
