#!/bin/bash
sync() {
mkdir -p ~/power
cd ~/power
git config --global user.name "ij_israfil"
git config --global user.email "israfilkhan494@gmail.com"
curl https://raw.githubusercontent.com/Shravan55555/build_script/refs/heads/main/infinity.sh | bash
}

echo "Syncing Rom and Device Sources..."
sync
echo "Syncing"
echo "Syncing...."
echo "Syncing......Done"
